import { StyleSheet, TextInput, View, Button, Text, ScrollView, FlatList } from 'react-native';
import { useState } from 'react';
import GoalItem from './components/GoalItem';
import GoalInput from './components/GoalInput';

export default function App() {
  const [courseGoals, setCourseGoals] = useState([]);

  {/*  */}
  function addGoalHandler(enteredGoalText) {
    setCourseGoals((currentCourseGoals) => [
      ...currentCourseGoals,
      /* Instead of the enteredGoalText only (a plain string), we change it into an object that has a key property by wrapping it into the curly braces. */
      {text: enteredGoalText, id: Math.random().toString()} /* id is the unique key for each item. */
      /* Course goals is now an array of objects that each object has a text property and an id property. */
    ]);
  }

  return (
    <View style = {styles.appContainer}>
      <GoalInput onAddGoal={addGoalHandler} />

      <Text style={styles.goalsTitle}>List of Goals</Text>

      {/* // Normal View - not scrollable */}
      {/* <View style={styles.goalsContainer}>
            {courseGoals.map((goal) => (
              <Text style={styles.goalItem} key={goal}>{goal}</Text>
            ))}
      </View> */}

      {/* ScrollView - make things scrollable */}
      {/* but it needs its parent to control the area it will take the height for the whole screen for that View. */}
      {/* The outer View controls how much space the area of the screen will take up. */}
      {/* The inner ScrollView makes sure the items in that space to be scrollable if they exceed the space. */}      
      {/* <View style={styles.goalsContainerView}>
        <ScrollView alwaysBounceHorizontal={false}>
              {courseGoals.map((goal) => (
                <View key={goal}>
                  <Text style={styles.goalItem}>{goal}</Text>
                </View>
              ))}
        </ScrollView>
      </View> */}

      {/* FlatList - better performance for large lists */}
      {/* FlatList won't render all the items at once, only the ones that are currently visible on the screen. */}
      {/* The rest of the items are rendered as the user scrolls through the list as it will use the lazy load*/}
      <View style={styles.goalsContainerView}>
        {/* FlatList requires a data prop and a renderItem prop to define how each item should be rendered. */}
        {/* Define a keyExtractor prop to specify how to extract unique keys for each item in the list. */}
        {/* Data prop takes the array of items to be displayed in the list. */}
        {/* renderItem prop is a function that takes an object with an item property (representing the current item) and returns a React element to be rendered for that item. */}
        {/* renderItem uses a function that will tell FlatList how to render each item in the list. */}
        {/* renderItem function will call its function whenever it needs to render an item because the user is scrolling to make the item visible, passing the current item as a prop. */}
        {/* item is an object generated by FlatList automatically and internally. The object that wraps around the individual item in the list. */}
        <FlatList data={courseGoals} renderItem={(itemData) => {
          return (
            <GoalItem text={itemData.item.text} />
          );
        }} 
          alwaysBounceHorizontal={false} 
          keyExtractor={(item, index) => {
          return item.id; // here we are returning the id property of each item as the unique key for that item.
        }}/>
        {/* keyExtractor prop is used to specify how to extract unique keys for each item in the list. It wants a function as a value. 
        It is used to call to get a key out of every item. It will be attached to the item by FlatList*/}
        {/* keyExtractor is different from the renderItem function. 
        renderItem is for JSX code to render each item, while keyExtractor is for getting the unique key for each item. */}
        {/* keyExtractor function receives two arguments: item (the current item being processed) and index (the index of the current item in the data array). */}
        {/* In FlatList, there are two ways to adding keys to the list item:
        1. Turn data values (from primitive types like strings or numbers) into object that has a key property. (Include: "text" and "key" property at the state)
        2. Using the key extractor */}
        {/* Its default prop for the object of the Flatlist is "key", but we can customize it to be any property we want, like "id" in this case by using the keyExtractor */}
      </View>
      
    </View>
  )
}

const styles = StyleSheet.create({
  appContainer: {
    flex: 1,
    paddingTop: 50,
    paddingHorizontal: 18,
  },
  goalsContainer: {
    flex: 5,
  },
  goalsTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
    marginTop: 10
  },
  goalsContainerView: {
    flex: 5,
  }
});